import { Metadata } from 'next'

import Hero from '@/components/hero'
import CardWrapper from '@/components/card-wrapper'
import Card from '@/components/card'

import heroImage from '@/public/assets/image/hero-image.png'
import cardImage from '@/public/assets/image/card-image.png'
import avatar from '@/public/assets/image/avatar.png'
import { getNews } from '@/actions/getNews'

export const metadata: Metadata = {
  title: 'Search',
  description: 'Generated by create next app',
}

export default async function Page({
  searchParams,
}: {
  searchParams: { [key: string]: string | string[] | undefined }
}) {
  const news = await getNews({ q: searchParams.q as string })

  if (!news?.articles || news?.articles?.length <= 0) {
    return 'Not Found!'
  }

  const [firstArticle, ...restArticles] = news.articles || []

  return (
    <div>
      <Hero
        image={firstArticle.urlToImage || heroImage.src}
        title={firstArticle.title}
        category="Unknown"
        user={{
          avatar: undefined,
          name: firstArticle.author || 'Unknown',
        }}
        date={firstArticle.publishedAt}
      />

      <CardWrapper className="mt-48">
        {restArticles.map((article, index) => (
          <Card
            key={index}
            image={article.urlToImage || cardImage.src}
            title={article.title}
            category="Unknown"
            user={{
              avatar: avatar.src,
              name: article.author || 'Unknown',
            }}
            date={article.publishedAt}
          />
        ))}
      </CardWrapper>
    </div>
  )
}
