import { Metadata } from 'next'

import Hero from '@/components/hero'
import CardWrapper from '@/components/card-wrapper'
import Card from '@/components/card'

import heroImage from '@/public/assets/image/hero-image.png'
import cardImage from '@/public/assets/image/card-image.png'
import avatar from '@/public/assets/image/avatar.png'
import { getNews } from '@/actions/getNews'

export const metadata: Metadata = {
  title: 'Homepage',
  description: 'Generated by create next app',
}

export default async function Page({
  params = { category: 'technology' },
}: {
  params: { category: string }
}) {
  const news = await getNews({ category: params.category })

  if (!news?.articles || news?.articles?.length <= 0) {
    return 'Not Found!'
  }

  const [firstArticle, ...restArticles] = news.articles || []

  return (
    <div>
      <Hero
        image={firstArticle.urlToImage || heroImage.src}
        title={firstArticle.title}
        category={params.category}
        user={{
          avatar: undefined,
          name: firstArticle.author || 'Unknown',
        }}
        date={firstArticle.publishedAt}
      />

      <CardWrapper className="mt-48">
        {restArticles.map((article, index) => (
          <Card
            key={index}
            image={article.urlToImage || cardImage.src}
            title={article.title}
            category={params.category}
            user={{
              avatar: avatar.src,
              name: article.author || 'Unknown',
            }}
            date={article.publishedAt}
          />
        ))}
      </CardWrapper>
    </div>
  )
}
